spring.application.name=tickets

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/**
spring.datasource.username=*****
spring.datasource.password=****

# JPA Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/***

# Redis Connection
spring.cache.type=redis
spring.data.redis.host=**
spring.data.redis.port=***

# Cache Configuration (TTL - Time to Live)
spring.cache.redis.time-to-live=600000

# Gmail SMTP Configuration
spring.mail.host=******
spring.mail.port=**
spring.mail.username=**
spring.mail.password=****
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true